version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7780:80"
    volumes:
      - ./application:/var/www/html/application
      - ./public_html:/var/www/html/public_html
      - ./assets:/var/www/html/assets
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: testing
      MYSQL_USER: user1
      MYSQL_PASSWORD: passwd
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d/

volumes:
  db_data:
